# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            bahr.dev
tagline:          'serverless on AWS'
description:      'Serverless software development on AWS with Michael Bahr.'
url:              https://bahr.dev

author:
  name:           'Michael Bahr'
  url:            https://twitter.com/bahrdev

paginate:         5

plugins:
  - jekyll-gist
  - jekyll-sitemap